### ISSUE TITLE
Response能否加入url日志

### ISSUE THREAD

**Issue by Congx** [fengzhizi715/saf-logginginterceptor#11]
1、由于app日志比较多，Request有url日志，一看就知道Request的请求链接是多少，但是Response没有，根据url去搜索Response搜索不到，筛选不是很方便。
![image](https://user-images.githubusercontent.com/11795328/89701407-53444d00-d969-11ea-8c5e-0b9d5459accd.png)
Response加入Request一样的红色框中日志

另外：去除边框这个功能做的很好，很多日志库格式化之后复制出来都带log的tag很不方便，很棒！
感谢

**Comment by fengzhizi715** [comment]
可以的，抽空我就加一下

**Comment by fengzhizi715** [comment]
hi @Congx  
我改好了，可以用新版本尝试一下
