### ISSUE TITLE
不打印Body信息

### ISSUE THREAD

**Issue by Chen-Xi-g** [fengzhizi715/saf-logginginterceptor#15]
我查看你的源码，当contentType等于null的时候，不会打印返回体内容。这种情况需要处理。
![image](https://user-images.githubusercontent.com/37918545/156885939-ddd0bccf-6b5e-4282-9119-a5890f2346a8.png)
![image](https://user-images.githubusercontent.com/37918545/156885967-a1cc64f4-ca8f-4662-945f-b67f3329239d.png)
![image](https://user-images.githubusercontent.com/37918545/156886313-286f740f-676e-41e6-80f8-2ac4a10c4ea7.png)

**Comment by fengzhizi715** [comment]
收到，我这2天有空改了

**Comment by Chen-Xi-g** [comment]
> 收到，我这2天有空改了

坐等，old 铁。

**Comment by fengzhizi715** [comment]
@Chen-Xi-g 很奇怪，刚才我curl那个地址发现是有 contentType 的，然后在本地跑一下也是可以打印body的。
如果还有问题的话，可以加我的微信：fengzhizi715
