### ISSUE TITLE
成功依赖了此库，却找不到AndroidLoggingInterceptor这个类

### ISSUE THREAD

**Issue by JiangShuLiang** [fengzhizi715/saf-logginginterceptor#16]
![微信截图_20221201093744](https://user-images.githubusercontent.com/20485764/204945077-806d47fc-9db3-4f7f-9fc3-a2dc13328f9c.png)

**Comment by JiangShuLiang** [comment]
找到原因了....自己项目集成的kotlin版本太低导致的。。。

**Comment by fengzhizi715** [comment]
你的 Kotlin 版本是多少? @JiangShuLiang

**Comment by JiangShuLiang** [comment]
> 你的 Kotlin 版本是多少? @JiangShuLiang

1.4.20
