### ISSUE TITLE
增加日志输出级别？ 我想将日志输出log.e打印

### ISSUE THREAD

**Issue by zguop** [fengzhizi715/saf-logginginterceptor#3]

**Comment by fengzhizi715** [comment]
目前已有debug模式，如果要输出级别的话，我考虑增加一下

**Comment by fengzhizi715** [comment]
hi @zguop ,在1.4.1版本已经支持。
例如可以这样使用：
LoggingInterceptor.Builder()
   .loggable(true) // TODO: 发布到生产环境需要改成false
   .logLevel(LoggingInterceptor.LogLevel.DEBUG)

**Comment by zguop** [comment]
thank
