### ISSUE TITLE
有问题

### ISSUE THREAD

**Issue by zguop** [fengzhizi715/saf-logginginterceptor#4]
我是这样配的
![image](https://user-images.githubusercontent.com/16206793/56468940-b9038180-6465-11e9-8ee5-8ff104b45b70.png)
然后在这里 
![image](https://user-images.githubusercontent.com/16206793/56468952-cfa9d880-6465-11e9-962d-5b208bc3602a.png)
发生错误
lateinit property requestTag has not been initialized

requestTag这个字段没有初始化！！

我用的是全局的这个tag吧 是不是这样用的

**Comment by fengzhizi715** [comment]
hi @zguop 加一下我微信吧，我抽空帮你看看
微信的id是github的账号id

**Comment by fengzhizi715** [comment]
新版本已经修复该bug
