### ISSUE TITLE
json返回的字段中的Url可以不要加转义字符吗？如图

### ISSUE THREAD

**Issue by ZevShiShi** [fengzhizi715/saf-logginginterceptor#9]
![QJ%5GJ)W2HI) GJ3Y8KB4V9](https://user-images.githubusercontent.com/41049129/86885158-60320e80-c127-11ea-8aad-6a020706bd5b.png)

**Comment by ZevShiShi** [comment]
![5(EWX$KTO $0LM5LYRT7 6D](https://user-images.githubusercontent.com/41049129/86888500-d9803000-c12c-11ea-9759-5ec658489e90.png)
看了作者源码，调试了下，传入msg对象时，并没有加斜杠，是经过JSONObject和JSONArray加进去的，作者有空替换一下message=message.replace("\\/", “/”)，这样就可以了

**Comment by fengzhizi715** [comment]
hi @ZevShiShi 
图片好像看不了，方便的话提交一个pr？我晚上合并一下

**Comment by ZevShiShi** [comment]
> hi @ZevShiShi
> 图片好像看不了，方便的话提交一个pr？我晚上合并一下

提交了，有空合下哈

**Comment by fengzhizi715** [comment]
@ZevShiShi 不好意思，昨天忘记了，已经合并发布新版本了
